# Generated by Django 3.1.7 on 2022-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasknumber', models.IntegerField()),
                ('taskdescription', models.CharField(max_length=70)),
            ],
        ),
    ]
